### ISSUE TITLE
basic-demo-self-deploy fails to process incoming events

### ISSUE THREAD

**Issue by bigman73** [box/box-skills-kit-nodejs#6]
The original code is crashing in index.js with a circular references JSON error, since the request event handler is not reading the body properly.

The correct way to handle requests with http.createServer is to handle them as streaming events

Here's a tested code that works properly (changes made to both deploy.js and index.js):

    const server = http.createServer((req, res) => {
        console.log('Box Skills Request received');

        let body = '';
        req.on('data', (chunk) => {
            body += chunk;
        });
        req.on('end', () => {
            console.log(`body = ${body}`);

            index.handler(body).then((resolve, reject) => {
                // Set the response HTTP header with HTTP status and Content type
                res.statusCode = 200;
                res.setHeader('Content-Type', 'text/plain');
                res.end('Skill Processed');
            });
        });
    });

**Comment by eshaverma** [comment]
Thank you @bigman73 for checking.. You could have a look at this review:
https://github.com/box/box-skills-kit-nodejs/pull/8 if you like.
