### ISSUE TITLE
skills-kit-library function fails to process incoming events

### ISSUE THREAD

**Issue by JokerD4nt0** [box/box-skills-kit-nodejs#7]
Greetings,

This is the first time I'm doing this on github.

Following [this tutorial](https://developer.box.com/docs/build-a-box-skill) I'm trying to connect MS Azure and Box skills.

At the step 7, I have an Azure Function ready to process incoming new files uploaded in my target folder in Box skills.
The triggered skills is working properly by calling the Azure Function.

But just after executing the Azure Function, I got the following issue on my Azure console :

Stack: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
[...]

The JSON.parse come from the function FilesReader in skill-kit-library.js, at line 131 as you can see [here](https://github.com/box/box-skills-kit-nodejs/blob/master/skills-kit-library/skills-kit-2.0.js).

It seem that the "body" argument , which came from the "event" argument, sended by Box itself, is not readable.

There is maybe something to do in the JS script to make it work but i dont know what.

If you have any advice to give me I will be verry grateful. :)

**Comment by eshaverma** [comment]
Hi @JokerD4nt0  so for the parse to work, you just need to pass the entire event.body into the Files Reader constructor as shown const filesReader = new FilesReader(event.body). But seems like you did try this, so how about you print it. You can try 

console.log(`${JSON.stringify(event)}`);


or if there are circular dependency, you can try- 

const util = require('util'); //don't need to add anything extra into package.json
console.log(`${util.inspect(event)}`);


If everything is setup correctly, you should be seeing an event body coming back as as well formatted json with a body field in it. If anything still doesn't work you can email / hangouts chat with me  at everma@box.com.


Thanks

**Comment by eshaverma** [comment]
basically your error happens if the what's coming is is not a properly formatted string that turns into a json.

**Comment by eshaverma** [comment]
@JokerD4nt0 we reached out my email to you. once you are back from your break, you can let us know if you need anything else.

**Comment by JokerD4nt0** [comment]
Hello @eshaverma and thank you verry much for your replies !

Well, I did try some **console.log(${JSON.stringify(event)});** before the line **const filesReader = new FilesReader(event.body)** but it didn't even appear in the Azure console.
The only thing I have is the same error : "unexpected token u [...]" or a error code -1 "failure of execution of the function".

The thing is I am not in command of what is coming from Box... it's look like the JSON event is wrote with "unexpected" instead of a "normal" JSON file with "{" at the begening and metadatas inside.

Thanks for you help anyway. I hope the Box skill's support will debug it, if the bug come from Box.
